sudo: false
os: linux
language: node_js
arch:
   - amd64
   - ppc64le
node_js:
  - "10"
  - "11"
  - "12"
  - "iojs"
  - "4"
  - "5"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=standard
script: "npm run-script $TEST_SUITE"
